server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: mongodb

  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///mysql?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java


mybatis:
  type-aliases-package: com.jk.xinx.pojo
  configuration:
    map-underscore-to-camel-case: true